# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop' # Rubyのformatter/linter
gem 'rubocop-rspec' # RuboCopをRSpec用に拡張
gem 'rspec' # Rubyのテスティングフレームワークのデファクト

gem 'activerecord' # Railsで使われるORM(単体でも使える)
gem 'pg' # ActiveRecord等で使うためのAdapter
gem 'ulid' # ULIDが使えるようになる
